
int abs(int);
int test_abs(int);
int bitAnd(int, int);
int test_bitAnd(int, int);
int bitMask(int, int);
int test_bitMask(int, int);
int bitXor(int, int);
int test_bitXor(int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int evenBits();
int test_evenBits();
int isEqual(int, int);
int test_isEqual(int, int);
int isLess(int, int);
int test_isLess(int, int);
int isNegative(int);
int test_isNegative(int);
int isNonZero(int);
int test_isNonZero(int);
int isPower2(int);
int test_isPower2(int);
int leastBitPos(int);
int test_leastBitPos(int);
int logicalNeg(int);
int test_logicalNeg(int);
int reverseBytes(int);
int test_reverseBytes(int);
int sum3(int, int, int);
int test_sum3(int, int, int);
