(function(){var f,d;(function(){typeof _mlK!="undefined"?d=window._mlK:(d=window._mlK=function(a){return new d.prototype.init(a)},typeof ac_info_ware=="undefined"&&(ac_info_ware={}),f=ac_info_ware,d.extend=function(a,c,b){b&&d.extend(a,b);for(var e in c)c.hasOwnProperty(e)&&(a[e]=c[e]);return a},d.extend(d,{ready:function(){d.isReady=1},idle:[1,1],getProtocol:function(){return"http://"},joinParameters:function(a,c){var b=[];if(c==",")for(var d in a)a.hasOwnProperty(d)&&Array.prototype.push.call(b,
a[d]);else if(c=="&")for(var h in a)a.hasOwnProperty(h)&&Array.prototype.push.call(b,h+"="+a[h]);return b.join(c)},createCacheBuster:function(){return Math.ceil(Math.random()*1E10)},getCookieEnabled:function(){return navigator.cookieEnabled?1:0},getFlashVersion:function(){var a="0,0,0,0";try{navigator.plugins&&navigator.plugins["Shockwave Flash"]?a=navigator.plugins["Shockwave Flash"].description:window.ActiveXObject&&new ActiveXObject("ShockwaveFlash.ShockwaveFlash")&&(a=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))}catch(c){}a=
a.match(/\d+/g);return a[0]},getPreviousUrl:function(){var a="";try{a=top.document.referrer}catch(c){try{a=document.referrer}catch(b){}}return encodeURIComponent(a)},getCharset:function(){var a="utf-8";return a=window.ActiveXObject?document.charset:document.characterSet},load:function(a,c,b,e){var h,j=/loaded|complete/i,i="ml_js01_$"+d.createCacheBuster();c?(h=document.createElement("script"),h.type="text/javascript",h.async=1,h.id=i,h.src=a,document.getElementsByTagName("head")[0].appendChild(h)):
(window.ActiveXObject&&(j=/complete/i),document.write('<script type="text/javascript" src="'+a+'" id="'+i+'"><\/script>'));if(h=d.$(i))h.onload=h.onreadystatechange=function(){if(!h.readyState||h.readyState.match(j))if(typeof b=="function"&&(b(),b=null),h&&h.parentNode)h.onload=h.onreadystatechange=null,h.parentNode.removeChild(h),h=null};e&&setTimeout(function(){if(h)typeof b=="function"&&(b(),b=null),h.src="javascript:void(0)"},e)},send:function(a,c){var b;if(!f.ts)f.ts=(new Date).getTime();a=a.replace("[timestamp]",
f.ts);c?(b=document.createElement("img"),b.style.display="none"):(b=document.createElement("script"),b.type="text/javascript",b.async=!0);document.body.insertBefore(b,document.body.firstChild);a.indexOf("cb=")===-1&&a.indexOf("admaster.com.cn")===-1&&a.indexOf("oadz.com/")===-1&&a.indexOf("doubleclick.net")===-1&&(a=a+(a.indexOf("?")>0?"&cb=":"?cb=")+Math.ceil(Math.random()*1E9));b.src=a},sendcmp:function(a){var c=document.createElement("iframe"),b=document.body.firstChild;c.style.display="none";
c.src="http://static.mlt01.com/cmpcf.htm#"+a;b.parentNode.insertBefore(c,b)},$:function(a){return typeof a=="string"?document.getElementById(a):a},cookie:function(a,c,b){if(typeof c!=="undefined"){if(c===null)c="",b=b||{},b.expires=-1;a=a+"="+c;b&&(b.expires&&(a+=";expires="+b.expires.toUTCString()),b.path&&(a+=";path="+b.path),b.domain&&(a+=";domain="+b.domain),b.secure&&(a+=";secure"));document.cookie=a}else return RegExp(";?"+a+"=([^;]*);?").test(document.cookie)?decodeURIComponent(RegExp.$1):
null},ga:function(a,c){typeof ac_info_ware==="undefined"&&(ac_info_ware={});typeof ac_info_ware[a]==="undefined"&&(ac_info_ware[a]={});typeof c!=="undefined"&&(ac_info_ware[a].mid=c);typeof ac_info_ware[a].mid==="undefined"&&(ac_info_ware[a].mid=-1);return ac_info_ware[a].mid},gak:function(a,c,b){typeof ac_info_ware==="undefined"&&(ac_info_ware={});typeof ac_info_ware[a]==="undefined"&&(ac_info_ware[a]={});typeof b!=="undefined"&&(ac_info_ware[a][c]=b);return ac_info_ware[a][c]},gas:function(){var a=
Array.prototype.slice.call(arguments,0),c=a[0],b=function(a,b){for(var c=1,g;g=b[c];++c){var e=d.gak(g,"imids"),f=d.gak(g,"mid");a!=f&&(f&&f!=-1&&(e?e.indexOf(f)==-1&&d.gak(g,"imids",[e,f].join(",")):d.gak(g,"imids",f+"")),d.gak(g,"mid",a))}},e=function(a){for(var b={},c=0;c<rem_inv_ware.mids.length-a;c++)for(var g=0,e;e=rem_inv_ware.aids[c][g];g++)b[e]||(b[e]=[]),b[e].push(rem_inv_ware.mids[c]);for(var f in b)if(a=d.gak(f,"imids")){c=[];g=0;for(e=b[f].length;g<e;g++)a.indexOf(b[f][g])==-1&&c.push(b[f][g]);
c.length&&d.gak(f,"imids",[a,c.join(",")].join(","))}else d.gak(f,"imids",b[f].join(","))};if(window.rem_invt){if(c!=-1){if(!rem_inv_ware.mids)rem_inv_ware.mids=[];if(!rem_inv_ware.aids)rem_inv_ware.aids=[];if(!rem_inv_ware.seq)rem_inv_ware.seq=[];rem_inv_ware.mids.push(c);rem_inv_ware.aids.push(a.slice(1));rem_inv_ware.seq[rem_inv_ware.x-1]=1}if(rem_inv_ware.seq&&c==-1)rem_inv_ware.seq[rem_inv_ware.x-1]&&rem_inv_ware.mids.length?(a=rem_inv_ware.mids.length,b(rem_inv_ware.mids[a-1],rem_inv_ware.aids[a-
1]),e(1)):e(0),rem_inv_ware.mids=rem_inv_ware.aids=rem_inv_ware.seq=null}else b(c,a.slice(1))},igas:function(a){for(var c in a)for(var b=a[c],e=0,h=b.length;e<h;e++){var f=b[e],i=d.gak(f,"imids");i&&i.indexOf(c)==-1?i+=","+c:i=c+"";d.gak(f,"imids",i)}},reload:function(a,c,b,e,f,j,i){var e=e||0,f=f||0,j=j||0,i=i||1,g=null,k=null,l=null,k=null,m="",n=!1;if(!e&&window.ac_info_ware&&ac_info_ware["$mltag_"+a])ac_info_ware[a].async=1,setTimeout(function(){ac_info_ware["$mltag_"+a].g();window.ac_info_ware["mltag_"+
a]&&ac_info_ware["mltag_"+a].erase()},c*1E3);if(e&&window.ac_info_ware&&ac_info_ware["$mltag_"+a]&&(ac_info_ware[a].async=1,k=ac_info_ware["$mltag_"+a],m=k.info("destid"),k=d.$("ml_js01_"+a),m&&d.$(m)?(l=d.$(m),n=!0):k&&k.parentNode&&(d.$("vs_anch_"+a)?l=d.$("vs_anch_"+a):(l=d.element("div",{id:"vs_anch_"+a},{border:"none",background:"none",margin:0,padding:0,fontSize:0,height:"1px",width:"1px",position:"absolute"}),k.parentNode.insertBefore(l,k)),n=!0),n))d["vs_"+a]?g=d["vs_"+a]:(g=d["vs_"+a]={},
g.t=null,g.starttm=function(){if(g.t==null)g.t=setTimeout(function(){window.ac_info_ware["$mltag_"+a].g();window.ac_info_ware["mltag_"+a]&&window.ac_info_ware["mltag_"+a].erase();g.stoptm()},c*1E3)},g.stoptm=function(){if(g.t)clearTimeout(g.t),g.t=null;if(g.interval)clearTimeout(g.interval),g.interval=null}),g.stoptm(),g.interval=setTimeout(function(){var a=null,a=!0,b=0,c=0,e=0,k=0;document.hasFocus&&(a=document.hasFocus());a?i?(e=d.getClient("height"),k=d.getClient("width"),l.getBoundingClientRect&&
(a=l.getBoundingClientRect(),b=a.top-(document.documentElement.clientLeft||document.body.clientLeft||0),c=a.left-(document.documentElement.clientTop||document.body.clientTop||0)),b>-j&&b<e&&c>-f&&c<k?g.starttm():g.stoptm()):g.starttm():g.stoptm();g.interval=setTimeout(arguments.callee,1E3)},1E3);b==0&&setTimeout(function(){location.reload()},c*1E3)},vmap:function(a){var c=new Date;c.setFullYear(c.getFullYear()+1);d.cookie("acaspvid",a.acvid,{expires:c,path:"/",domain:location.host})},element:function(a,
c,b,e){a=document.createElement(a);if(c)for(var f in c)a.setAttribute(f,c[f]);b&&d.css(a,b);if(e)a.innerHTML=e;return a},css:function(a,c){var b=d.$(a);if(typeof c=="string"){if(b.currentStyle)return b.currentStyle[c];if(window.getComputedStyle)return document.defaultView.getComputedStyle(b,null)[c]}else if(typeof c=="object")for(var e in c)b.style[e]=c[e]},getClient:function(a){a=a.charAt(0).toUpperCase()+a.substr(1).toLowerCase();return document.compatMode=="BackCompat"?document.body["client"+a]:
document.documentElement["client"+a]},getScroll:function(a){a=a.charAt(0).toUpperCase()+a.substr(1).toLowerCase();return document.documentElement["scroll"+a]||document.body["scroll"+a]},getPosition:function(a){var a=d.$(a),c={left:0,top:0};if(a.getBoundingClientRect)c.left=Math.round(a.getBoundingClientRect().left+d.getScroll("left")-(document.documentElement.clientLeft||document.body.clientLeft||0)),c.top=Math.round(a.getBoundingClientRect().top+d.getScroll("top")-(document.documentElement.clientTop||
document.body.clientTop||0));return c},isFirstScreen:function(a,c,b){var e=0,f=d.getClient("height"),j=0,i=d.$("ml_js01_"+a),g=null;if(c&&d.$(c))j=d.getPosition(c).top;else if(b)j=b[0];else if(i)g=d.element("div",{id:"vs_anch_"+a},{border:"none",background:"none",margin:0,padding:0,fontSize:0,height:"1px",width:"1px",position:"absolute"}),i.parentNode.insertBefore(g,i),j=d.getPosition(g).top,g.parentNode.removeChild(g);f&&(e=Math.ceil(j/f));return e}}),d.prototype={init:function(a){if(a&&(a.aids||
a.aid)){if(a.aids)for(var c=0,b;b=a.aids[c];++c)f[b]?f[b].rl=0:f[b]={rl:0};var e="ml_js01_"+a.aid;(function(){if(!d.$(e)){var a=document.getElementsByTagName("script"),b=a.length,c=document.createElement("script");c.id=e;a[b-1].parentNode.insertBefore(c,a[b-1])}})();this.timestamp=(new Date).getTime();this.aid=a.aid;f["ml"+this.aid]?d.extend(f["ml"+this.aid],a):f["ml"+this.aid]=a;f["$mltag_"+this.aid]=this;this.info("mode")===1&&(this.info("rl")===0?(this.info("rl",1),f.otlads&&f.otlads[this.aid]&&
(f.otlads[this.aid](),f.otlads[this.aid]=null)):this.g())}},jsv:7,info:function(a,c){var b="ml"+this.aid;typeof f=="undefined"&&(f={});f[b]||(f[b]={});typeof c!="undefined"&&(c===null?delete f[b][a]:f[b][a]=c);return f[b][a]},getParameters:function(){var a=this.info("pv")||1,c=this.info("mid")===void 0?-1:this.info("mid"),b=this.info("imids")===void 0?0:this.info("imids"),e=d.joinParameters({aid:this.info("aid"),gid:this.info("gid")===void 0?0:this.info("gid"),format:this.info("format")===void 0?
0:this.info("format"),mode:this.info("mode")===void 0?1:this.info("mode"),ce:d.getCookieEnabled(),fv:d.getFlashVersion()},","),a={pv:a,sp:e,ec:d.getCharset(),re:[screen.width,screen.height].join(",")};if(this.info("aids"))a.clt=this.info("aids").join(",");c!=-1&&(a.mid=c);b&&(a.imids=b);if(this.info("gid")===1&&typeof ac_content_targeting!="undefined"&&ac_content_targeting)a.ct=encodeURIComponent(ac_content_targeting);this.info("ex")&&d.extend(a,this.info("ex"));if(d.getPreviousUrl())a.purl=d.getPreviousUrl();
a.jsv=this.jsv;a.cb=d.createCacheBuster();d.seq?d.seq+=1:d.seq=1;a.seq=d.seq;if(d.cookie("acaspvid"))a.vid=d.cookie("acaspvid");a.fs=d.isFirstScreen(this.aid,this.info("destid"),this.info("coors"));return d.joinParameters(a,"&")},getServerUrl:function(){return d.getProtocol()+this.getBaseUrl()+"ia.htm?"},getBaseUrl:function(){return this.info("serverbaseurl")?this.info("serverbaseurl"):this.getLBUrl()},getLBUrl:function(){return this.info("serverbaseurl",this.info("gid")===1?"mlt01.com/":"mlt01.com/")},
g:function(a,c){var b=this;(new Date).getTime();var e;c||b.info("async")?(e=function(){d.idle[1]=1},function(){d.idle[0]&&d.idle[1]?(d.idle[1]=0,d.load(a||b.getServerUrl()+b.getParameters(),c||b.info("async"),e,1E4)):setTimeout(arguments.callee,0)}()):(d.idle[0]=0,e=function(){d.idle[0]=1},d.load(a||b.getServerUrl()+b.getParameters(),c||b.info("async"),e,1E4))}},d.prototype.init.prototype=d.prototype)})();(function(){typeof _mlKOTL=="undefined"&&(_mlKOTL=function(){for(var a=Array.prototype.slice.call(arguments,
0),c=a[a.length-1],a=a.slice(0,-1),b=a.splice(0,16);b.length;)d({aid:0,aids:b,gid:1,format:0,mode:1,serverbaseurl:c}),b=a.splice(0,16)})})();(function(){var a={pv:1,gid:0,format:0,mode:1,staticbaseurl:"mlt01.com/"};if(typeof ac_as_id=="number"){a.aid=ac_as_id;a.pv=1;ac_as_id=null;if(typeof ac_group_id=="number")a.gid=ac_group_id,a.groupid=ac_group_id,ac_group_id=null;if(typeof ac_format=="number")a.format=ac_format,ac_format=null;if(typeof ac_mode=="number")a.mode=ac_mode,ac_mode=null;if(a.gid===
0)a.async=1;if(typeof ac_async=="number")a.async=ac_async,ac_async=null;if(typeof ac_dest_id!="undefined")a.destid=ac_dest_id,ac_dest_id=null;if(typeof ac_anch_id!="undefined")a.anchid=ac_anch_id,ac_anch_id=null;if(typeof ac_coors!="undefined")a.coors=ac_coors,ac_coors=null;if(typeof ac_static_base_url=="string"&&ac_static_base_url)a.staticbaseurl=ac_static_base_url,ac_static_base_url=null;if(typeof ac_server_base_url=="string"&&ac_server_base_url)a.serverbaseurl=ac_server_base_url,ac_server_base_url=
null;if(typeof ac_ad_none=="function")a.ad_none=ac_ad_none,ac_ad_none=null;if(typeof ac_show_end=="function")a.show_end=ac_show_end,ac_show_end=null;d(a)}})()})();
